AWSTemplateFormatVersion: 2010-09-09
Description: FridayHITT Network Stack

Parameters:
  VpcCidrBlock:
    Description: VPC CIDR block
    Type: String
    Default: 10.0.0.0/16
    ConstraintDescription: Must be a valid CIDR block

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-InternetGateway'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: eu-west-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PublicSubnet1'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-1b
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PublicSubnet2'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-1a
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PrivateSubnet1'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: eu-west-1b
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PrivateSubnet2'
        - Key: Environment
          Value: Test
        - Key: Owner
          Value: Arek
        - Key: Application
          Value: Friday-HITT
        - Key: CostCenter
          Value: Marketing
        - Key: Project
          Value: ProjectA

Outputs:
  VpcId:
    Description: ID of the VPC
    Value: !Ref VPC
  PublicSubnet1Id:
    Description: ID of the public subnet 1
    Value: !Ref PublicSubnet1
  PublicSubnet2Id:
    Description: ID of the public subnet 2
    Value: !Ref PublicSubnet2
  PrivateSubnet1Id:
    Description: ID of the private subnet 1
    Value: !Ref PrivateSubnet1
  PrivateSubnet2Id:
    Description: ID of the private subnet 2
    Value: !Ref PrivateSubnet2
